name: cd
on:
  #schedule:
  #  - cron:  '0 8,14 * * *'
  push:
    branches: 
      - main
jobs:
  download-data-and-audit-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Run the CLI command to download consolidated data
        run: |
          pipenv run python . download
      - name: Run the quality audit on first 1000 rows
        run: |
          pipenv run python . audit --rows 1000
      - name: Upload audit results as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: audit-1000lignes.json
          path: ./data/audit-1000lignes.json
          retention-days: 90