#https://docs.streamlit.io/library/advanced-features/configuration

[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#325682"

# Background color for the main content area.
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#D8e8F4"

# Color used for almost all text.
textColor = "#1f2b50"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"